# Generated by Django 4.2.7 on 2023-12-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
