# Generated by Django 4.2.7 on 2023-12-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imageURL',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
