# Generated by Django 4.2.7 on 2023-12-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='imageURL',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
