# Generated by Django 4.2.7 on 2023-12-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_imageurl_auction_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='headline',
        ),
    ]
